# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site change start
# Site
# blog's title
title: 一叶扁舟

# subtitle in the banner header
subtitle: 一叶扁舟

# introduction  in the banner header
subtitle_desc: 日常学习与兴趣交流

# seo keyword
keywords: blog, 前端博客, 前端, java, 前端开发, 全栈开发, node.js, javascript

# blog description（for seo）
description: 个人博客，用于分享一些在日常学习工作总结。胡言乱语，望各位看官见谅。

# self introduction
introduction: 不思量，自难忘！

# your blog favicon icon, support two ways: local and online. the local way need you to put the icon under  themes/hexo-theme-skapp/source/img directory
#favicon_ico: http://oo12ugek5.bkt.clouddn.com/blog/images/favicon.ico
favicon_ico: /assets/qiniu/favicon.ico
#favicon_ico: '@{qiNiu}/favicon.ico'

# blog logo icon in the upper left corner. support the local way and online way.
logo: '@{qiNiu}/images/logo-text-white.png'

# avatar
#avatar: http://oo12ugek5.bkt.clouddn.com/images/qrcode.png
qrcode: '@{qiNiu}/images/apcode.png'
# qrcode: http://oo12ugek5.bkt.clouddn.com/images/qrcode.png

# page default cover
default_cover: '@{qiNiu}/images/page-cover-default.gif'

# header background picture
#header_cover: http://oo12ugek5.bkt.clouddn.com/blog/images/banner-bg.jpg
header_cover: '@{qiNiu}/images/blog-bg.jpg'

# 404 page background picture
error_page_bg: http://oo12ugek5.bkt.clouddn.com/blog/images/dogs.jpg

# page loading icon
loader_img: http://oo12ugek5.bkt.clouddn.com/blog/images/loader.gif

# author information
author: brian
authorLink: https://brianhuangxp.github.io
language: zh-cn

# footer information
about:
  info: 本站是基于 Hexo 搭建的静态资源博客，主要用于分享日常学习、生活及工作的一些心得总结，欢迎点击右下角订阅 rss。
  address: Xiamen, Fujian Province, China
  email: huangkingxp@126.com
# Site change end

timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://brianhuangxp.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-skapp

## change start
# Sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Autoprefixer
autoprefixer:
  exclude:
    - '*.min.css'
  browsers:
    - 'last 2 versions'

# Lunr
lunr:
  field: all
  fulltext: false
  path: assets/lunr/

# filter_cleanup
hfc_useref:
  enable: true
  concat: true

hfc_html:
  enable: true
  exclude:

hfc_css:
  enable: true
  exclude:
    - '*.min.css'

hfc_js:
  enable: true
  mangle: true
  exclude:
    - '*.min.js'

hfc_img:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

hfc_favicons:
  enable: false
  src: img/blog-logo.png
  target: img/
  icons:
    android: true
    appleIcon: true
    appleStartup: false
    coast: false
    favicons: true
    firefox: false
    opengraph: false
    windows: true
    yandex: false

menu:
  home: /
  archive: /archives
#  categories: /categories
#  tags: /tags
  about: /about

# Busuanzi
busuanzi: true
## change end

archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: https://github.com/brianhuangxp/brianhuangxp.github.io
    branch: master

# common parameter filter
## @{qiNiu} in post.md file, it will replace with the value of qiNiu
commonParametersFilter:
  clouldResourceDomain:
    qiNiu: http://pgzciqfe6.bkt.clouddn.com
    css3Animat: https://huangking.gitee.io/css3-animat
    myDojo: https://brianhuangxp.github.io/my-dojo